import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
// import { SessionProvider } from "next-auth/react";
import { getServerSession } from "next-auth";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Wave Nanthawat",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const session = await getServerSession(authOptions);

  // return (
  //   <html lang="en">
  //     <body>
  //       <Providers session={session}>{children}</Providers>
  //     </body>
  //   </html>
  // );
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
